services:
  postgres:
    image: postgres:17-alpine
    container_name: toverni-postgres

    environment:
      POSTGRES_USER: toverni
      POSTGRES_PASSWORD: toverni
      POSTGRES_DB: toverni

    ports:
      - "55432:5432"

    volumes:
      - toverni_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U toverni -d toverni"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  toverni_postgres_data: